services:
  firebase:
    container_name: firebase-emulator
    stdin_open: true # docker run -i
    tty: true # docker run -t
    build: .
    ports:
      - "4000-4040:4000-4040"
    develop:
      watch:
        - action: sync
          path: .
          target: /app
