name: Preview Web App on Firebase Hosting

on:
  pull_request:
    branches:
      - main
      - dev
    paths:
      - 'web/**'

jobs:
  build_and_preview:
    if: github.event_name == 'pull_request'
    permissions:
      contents: 'read'
      checks: 'write'
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm ci && npm run build
        working-directory: ./web
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          firebaseServiceAccount: ${{ secrets.SERVICE_ACCOUNT_JSON_KEY }}
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          projectId: ${{ secrets.GCP_PROJECT_ID }}
          channelId: preview
          entryPoint: ./web
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks
