name: Preview Web App on Firebase Hosting

on:
  pull_request:
    branches:
      - main
      - dev
    paths:
      - 'web/**'

jobs:
  build_and_preview:
    if: github.event_name == 'pull_request'
    permissions:
      contents: 'read'
      id-token: 'write'
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Install dependencies and build
        working-directory: ./web
        run: |
          npm ci
          npm run build

      - name: Deploy to Firebase Hosting preview channel
        id: deploy
        working-directory: ./web
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FIREBASE_CLI_EXPERIMENTS: webframeworks
        run: |
          deploy_output=$(firebase hosting:channel:deploy pr-${{ github.event.number }} --project=${{ secrets.GCP_PROJECT_ID }} --expires=1h --json | tail -n 1)
          echo "$deploy_output"
          echo "deploy_output=$deploy_output" >> $GITHUB_OUTPUT

      - name: Add preview URL to PR comment
        uses: actions/github-script@v6
        with:
          script: |
            const output = JSON.parse('${{ steps.deploy.outputs.deploy_output }}');
            if (output.status === undefined || output.result === undefined || output.status === "error") {
              console.log(output);
            } else {
              const results = Object.values(output.result);
              const expireTime = results[0].expireTime;
              const expire_time_formatted = new Date(expireTime).toUTCString();
              const urls = results.map((siteResult) => siteResult.url);
              const url = urls.length === 1
                ? `[${urls[0]}](${urls[0]})`
                : urls.map((url) => `- [${url}](${url})`).join("\n");
              const body = `
                ðŸš€ Visit the preview URL for this PR (updated for commit ${commit}):

                ${url}

                <sub>(expires ${expire_time_formatted})</sub>
              `.trim();
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body,
              });
            }